# Site settings
title:     		Devmatic
email: 			bart.jedrocha@gmail.com
author:      	Bart Jedrocha
description: 	"The blog and portfolio of Bart Jedrocha, Software Engineer"
baseurl:     	""
url:         	"http://bjedrocha.com"

# Gems
gems: [jekyll-paginate]

# Google analytics
google_analytics: UA-60630844-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true
show_sharing_icons: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: devmatic

# Social icons
github_username: bjedrocha
stackoverflow_id: 85125
twitter_username: bjedrocha
google_plus_id:
linkedin_username: bjedrocha
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Sharing icons
share_text: 'Share this post!'
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
