# Site settings
title:     		Devmatic
email:       	bart@devmatic.ca
author:      	Bart Jedrocha
description: 	"Devmatic is the blog and portfolio of Bart Jedrocha"
baseurl:     	""
url:         	"http://bjedrocha.github.io"
# url: 		  	"http://localhost:4000"

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: bjedrocha
stackoverflow_id: 
twitter_username: bjedrocha
google_plus_id:
linkedin_username: bjedrocha
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
